name: Build Game for Windows

on:
  push:
    branches: [ "main" ]  # Запускать при каждом обновлении кода в ветке main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pynput pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --console main.py

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: MyMazeGame
        path: dist/main.exe
